name: Run E2E tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json
      - name: Install dependencies
        run: npm install
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          APP_URL: "http://localhost:3000"  
          NEXT_PUBLIC_API_BASE_URL: "http://ignite-devstore-api-three.vercel.app"
        with:
          build: npm run build
          start: npm start